### ISSUE TITLE
Non-exhaustive patterns in function plain

### ISSUE THREAD

**Issue by snoyberg** [batterseapower/ansi-wl-pprint#6]
My most recent stackage builds just had a bunch of test suite failures with the following text:

```
         Test Cases     Total         test-async: Text/PrettyPrint/ANSI/Leijen.hs:(1039,1)-(1053,39): Non-exhaustive patterns in function plain
```

This seems to have been triggered by usage of test-framework. This is based on version 0.6.7 of the package.

**Comment by batterseapower** [comment]
Thanks. Does v0.6.7.1 fix it?

**Comment by snoyberg** [comment]
Looks like it's solved to me, thanks!
